/**
 * Prometheus metric registry — every series the server exposes is declared here.
 *
 * Three families:
 *   1. HTTP  — request duration histogram + count + in-flight, labelled by
 *      method/route/status. This is the RED-method (Rate, Errors, Duration)
 *      surface the old gauges-only endpoint lacked. Route is the express route
 *      TEMPLATE (e.g. /api/conversations/:id), never the raw URL, to bound
 *      cardinality and avoid leaking ids.
 *   2. Workers — counters for the summary + vector backfill sweeps (work done,
 *      failures) and the live AIMD concurrency gauge.
 *   3. Capacity / security / business — gauges refreshed on each scrape from the
 *      database (see routes/metrics.ts). Declared here so they live in one
 *      registry and render together.
 *
 * Default process/Node metrics (CPU, memory, event-loop lag, GC) are collected
 * too — cheap and invaluable for capacity work.
 */
import {
  Registry, Counter, Gauge, Histogram, collectDefaultMetrics,
} from 'prom-client';

export const registry = new Registry();

collectDefaultMetrics({ register: registry, prefix: 'chatrecall_' });

// ── 1. HTTP ────────────────────────────────────────────────────────────────
export const httpRequestDuration = new Histogram({
  name: 'chatrecall_http_request_duration_seconds',
  help: 'HTTP request latency in seconds',
  labelNames: ['method', 'route', 'status'] as const,
  // Tuned for a JSON API: sub-ms static routes up to multi-second search/analytics.
  buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
  registers: [registry],
});

export const httpRequestsTotal = new Counter({
  name: 'chatrecall_http_requests_total',
  help: 'Total HTTP requests handled',
  labelNames: ['method', 'route', 'status'] as const,
  registers: [registry],
});

export const httpRequestsInFlight = new Gauge({
  name: 'chatrecall_http_requests_in_flight',
  help: 'HTTP requests currently being processed',
  registers: [registry],
});

// ── 2. Workers ───────────────────────────────────────────────────────────────
export const summarySweepsTotal = new Counter({
  name: 'chatrecall_summary_sweeps_total',
  help: 'Summary worker sweeps run',
  labelNames: ['result'] as const, // 'ok' | 'error'
  registers: [registry],
});
export const summariesGeneratedTotal = new Counter({
  name: 'chatrecall_summaries_generated_total',
  help: 'Session summaries generated by the worker',
  registers: [registry],
});
export const summariesFailedTotal = new Counter({
  name: 'chatrecall_summaries_failed_total',
  help: 'Session summary generation failures',
  registers: [registry],
});
export const summariesSkippedTotal = new Counter({
  name: 'chatrecall_summaries_skipped_total',
  help: 'Sessions skipped by the summary worker (trivial/over-quota)',
  registers: [registry],
});
export const summaryConcurrency = new Gauge({
  name: 'chatrecall_summary_concurrency',
  help: 'Current AIMD-tuned summary worker concurrency',
  registers: [registry],
});

export const vectorSweepsTotal = new Counter({
  name: 'chatrecall_vector_backfill_sweeps_total',
  help: 'Vector backfill sweeps run',
  labelNames: ['result'] as const, // 'ok' | 'error'
  registers: [registry],
});
export const vectorsEmbeddedTotal = new Counter({
  name: 'chatrecall_vectors_embedded_total',
  help: 'Chunks embedded by the vector backfill worker',
  registers: [registry],
});

// ── 3. Capacity / security gauges (refreshed per scrape from the DB) ──────────
export const gUp = new Gauge({ name: 'chatrecall_up', help: '1 when the server can read its database', registers: [registry] });
export const gSessions = new Gauge({ name: 'chatrecall_sessions_total', help: 'Indexed sessions across all tenants', registers: [registry] });
export const gChunks = new Gauge({ name: 'chatrecall_chunks_total', help: 'Searchable text chunks across all tenants', registers: [registry] });
export const gRawSessions = new Gauge({ name: 'chatrecall_raw_sessions_total', help: 'Stored raw (redacted) session archives', registers: [registry] });
export const gSecretFindings = new Gauge({ name: 'chatrecall_secret_findings_total', help: 'Secret findings across all tenants', registers: [registry] });
export const gSecretFindingsVerified = new Gauge({ name: 'chatrecall_secret_findings_verified', help: 'Secret findings confirmed LIVE by the verifier — alert on this', registers: [registry] });
export const gTenants = new Gauge({ name: 'chatrecall_tenants_total', help: 'Provisioned tenants', registers: [registry] });

export const gPoolTotal = new Gauge({ name: 'chatrecall_pg_pool_total', help: 'pg pool connections open', registers: [registry] });
export const gPoolIdle = new Gauge({ name: 'chatrecall_pg_pool_idle', help: 'pg pool connections idle', registers: [registry] });
export const gPoolWaiting = new Gauge({ name: 'chatrecall_pg_pool_waiting', help: 'requests waiting for a pg connection — alert if sustained >0', registers: [registry] });

// Work backlog (also served as JSON to KEDA at /metrics/backlog) — exposing it
// to Prometheus too lets us alert/graph drain rate, not just scale on it.
export const gPendingVectors = new Gauge({ name: 'chatrecall_pending_vectors', help: 'Chunks awaiting embedding across all tenants', registers: [registry] });
export const gPendingSummaries = new Gauge({ name: 'chatrecall_pending_summaries', help: 'Sessions awaiting a summary across all tenants', registers: [registry] });
export const gPendingRealSummaries = new Gauge({ name: 'chatrecall_pending_real_summaries', help: 'Non-trivial sessions awaiting an LLM summary — the OVMS scale signal', registers: [registry] });

// ── 3b. Business / SaaS gauges (refreshed per scrape from the control plane) ──
export const gSubscriptions = new Gauge({
  name: 'chatrecall_subscriptions',
  help: 'Tenants by subscription status',
  labelNames: ['status'] as const, // active|trialing|past_due|canceled|none
  registers: [registry],
});
export const gSubscriptionsByPlan = new Gauge({
  name: 'chatrecall_subscriptions_by_plan',
  help: 'Tenants by plan and subscription status',
  labelNames: ['plan', 'status'] as const,
  registers: [registry],
});
export const gMrrUsd = new Gauge({ name: 'chatrecall_mrr_usd', help: 'Monthly recurring revenue (active subscriptions × plan price, USD)', registers: [registry] });
export const gTrialsActive = new Gauge({ name: 'chatrecall_trials_active', help: 'Tenants currently in a paid trial', registers: [registry] });
export const gTrialsExpiring24h = new Gauge({ name: 'chatrecall_trials_expiring_24h', help: 'Trials whose period ends within 24h', registers: [registry] });
export const gTeamsTotal = new Gauge({ name: 'chatrecall_teams_total', help: 'Teams (signups)', registers: [registry] });
export const gMembersTotal = new Gauge({ name: 'chatrecall_members_total', help: 'Team memberships (seats)', registers: [registry] });
export const gSignups24h = new Gauge({ name: 'chatrecall_signups_24h', help: 'Teams created in the last 24h', registers: [registry] });
export const gConversions24h = new Gauge({ name: 'chatrecall_conversions_24h', help: 'Subscriptions that became active in the last 24h', registers: [registry] });
export const gChurn24h = new Gauge({ name: 'chatrecall_churn_24h', help: 'Subscriptions canceled in the last 24h', registers: [registry] });
