import { describe, test, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { extractFirstUserPrompt, extractFirstUserPromptSync } from './first-prompt.js';

let tmp: string;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'cr-firstprompt-'));
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

function writeJsonl(name: string, lines: object[]): string {
  const p = join(tmp, name);
  writeFileSync(p, lines.map(l => JSON.stringify(l)).join('\n') + '\n');
  return p;
}

// User message with string content (oldest Claude format)
function userStr(text: string, isSidechain = false) {
  return { type: 'user', isSidechain, message: { role: 'user', content: text } };
}

// User message with array-of-blocks content (current format)
function userBlocks(text: string, isSidechain = false) {
  return {
    type: 'user',
    isSidechain,
    message: { role: 'user', content: [{ type: 'text', text }] },
  };
}

describe('extractFirstUserPromptSync', () => {
  test('returns first user prompt from string-content format', () => {
    const f = writeJsonl('s1.jsonl', [
      { type: 'system', message: 'init' },
      userStr('help me debug the auth flow'),
      userStr('also check the logs'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('help me debug the auth flow');
  });

  test('returns first user prompt from array-of-blocks format', () => {
    const f = writeJsonl('s2.jsonl', [
      userBlocks('rewrite this function in TypeScript'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('rewrite this function in TypeScript');
  });

  test('skips system reminders embedded in user messages', () => {
    // Hooks and the harness wrap the actual prompt with <system-reminder>
    // tags. The previous extractor surfaced the wrapped envelope as if it
    // were the user's first prompt — this test guards the regression.
    const f = writeJsonl('s3.jsonl', [
      userBlocks('<system-reminder>Auto-mode reminder</system-reminder>'),
      userBlocks('the actual real prompt comes second'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('the actual real prompt comes second');
  });

  test('skips sidechain (agent-injected) prompts', () => {
    // When a parent agent dispatches a Task subagent, the subagent's first
    // user message is auto-generated by the parent and tagged
    // isSidechain: true. That's not the human's prompt and shouldn't be
    // treated as one.
    const f = writeJsonl('s4.jsonl', [
      userBlocks('Conduct a comprehensive audit of the codebase…', /*isSidechain*/ true),
      userBlocks('actual user request'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('actual user request');
  });

  test('skips messages shorter than 10 chars after banner stripping', () => {
    // Single-word interjections aren't useful titles.
    const f = writeJsonl('s5.jsonl', [
      userBlocks('ok'),
      userBlocks('go'),
      userBlocks('write the migration script for adding the user table'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('write the migration script for adding the user table');
  });

  test('strips MCP issues and Context-low banners', () => {
    // Claude Code prepends these banners to the first user message when
    // certain transient errors fire. They leaked into titles before — the
    // banner-stripper is what stops "MCP issues detected. Run /mcp list"
    // from showing up as a session title.
    const f = writeJsonl('s6.jsonl', [
      userBlocks('MCP issues detected. Run /mcp list for status. fix the build please'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('fix the build please');
  });

  test('skips synthetic [Request interrupted by user] placeholder', () => {
    const f = writeJsonl('s7.jsonl', [
      userBlocks('[Request interrupted by user]'),
      userBlocks('continue with the previous task'),
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('continue with the previous task');
  });

  test('truncates to maxLength', () => {
    const long = 'a'.repeat(2000);
    const f = writeJsonl('s8.jsonl', [userBlocks(long)]);
    const out = extractFirstUserPromptSync(f, { maxLength: 50 });
    expect(out.length).toBe(50);
    expect(out).toBe('a'.repeat(50));
  });

  test('respects maxLines bound — no infinite scan on giant files', () => {
    // Hand-build a session where the only user prompt is past the maxLines
    // cap. The extractor must give up cleanly rather than read forever.
    const lines: object[] = [];
    for (let i = 0; i < 100; i++) lines.push({ type: 'system', message: 'noise' });
    lines.push(userBlocks('this prompt is past the cap'));
    const f = writeJsonl('s9.jsonl', lines);
    expect(extractFirstUserPromptSync(f, { maxLines: 50 })).toBe('');
    // Sanity: with a higher cap, it succeeds.
    expect(extractFirstUserPromptSync(f, { maxLines: 200 })).toBe('this prompt is past the cap');
  });

  test('returns empty string for missing file (no throw)', () => {
    expect(extractFirstUserPromptSync(join(tmp, 'does-not-exist.jsonl'))).toBe('');
  });

  test('survives malformed JSON lines', () => {
    // A truncated/corrupt write shouldn't break the rest of the parse.
    const p = join(tmp, 'corrupt.jsonl');
    writeFileSync(p,
      '{not valid json\n' +
      JSON.stringify(userBlocks('the recoverable prompt after corruption')) + '\n'
    );
    expect(extractFirstUserPromptSync(p)).toBe('the recoverable prompt after corruption');
  });

  test('returns empty when there are no user messages at all', () => {
    const f = writeJsonl('only-system.jsonl', [
      { type: 'system', message: 'init' },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
    ]);
    expect(extractFirstUserPromptSync(f)).toBe('');
  });
});

describe('extractFirstUserPrompt (async)', () => {
  test('matches the sync variant on the same input', async () => {
    const f = writeJsonl('async.jsonl', [
      userBlocks('<system-reminder>noise</system-reminder>'),
      userBlocks('the real first prompt for the async path'),
    ]);
    const sync = extractFirstUserPromptSync(f);
    const asyncResult = await extractFirstUserPrompt(f);
    expect(asyncResult).toBe(sync);
    expect(asyncResult).toBe('the real first prompt for the async path');
  });

  test('returns empty for missing file (no throw)', async () => {
    await expect(extractFirstUserPrompt(join(tmp, 'no.jsonl'))).resolves.toBe('');
  });
});
